trigger:
  - main

pool: 
 vmImage: 'windows-latest'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              command: 'build'
              projects: '**/pipeline-001.slnx'
              arguments: '-c Release -f net10.0'
  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: DeployJob
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'dotnet publish'
            inputs:
              command: 'publish'
              projects: '**/pipeline-001.slnx'
              arguments: '-c Release -f net10.0 --output $(Build.ArtifactStagingDirectory)'
              publishWebProjects: false
              zipAfterPublish: true
          - task: PublishBuildArtifacts@1
            displayName: 'Publish artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
